name: dev build

on:
  push:
    branches:
      - dev

jobs:
  mac_build:
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm

      - name: Install Dependencies
        run: npm install

      - name: Build for macOS
        run: npm run build:mac

      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: splayer-macos
          path: release/*/splayer-mac-*-universal.dmg
          if-no-files-found: ignore

  windows_build:
    runs-on: windows-latest
    timeout-minutes: 30

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm

      - name: Install Dependencies
        run: npm install

      - name: Build for Windows
        run: npm run build:win

      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: splayer-windows
          path: release/*/*Setup*.exe
          if-no-files-found: ignore

  linux_build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm

      - name: Install Dependencies
        run: npm install

      - name: Build for Linux
        run: npm run build:linux

      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: splayer-linux
          path: |
            splayer*.AppImage
            splayer*.tar.gz
          if-no-files-found: ignore
