name: Build Dev

on:
  push:
    branches:
      - dev

jobs:
  release:
    name: Build and electron app
    runs-on: windows-latest

    steps:
      - name: Check out git repository
        uses: actions/checkout@v3.0.0

      - name: Install Node.js
        uses: actions/setup-node@v3.0.0
        with:
          node-version: "16.x"

      - name: Install Dependencies
        run: npm install

      - name: Build Electron App
        run: npm run build:win
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Cleanup Artifacts
        run: |
          npx rimraf "dist/!(*.exe)"

      - name: Upload artifacts
        uses: actions/upload-artifact@v3.0.0
        with:
          name: SPlayer-dev
          path: dist

      - name: Create a release
        uses: softprops/action-gh-release@v0.1.14
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          draft: true
          files: "dist/**"
