name: Build

on:
  push:
    branches:
      - dev
    tags:
      - v*
jobs:
  release:
    name: Build and release electron app
    runs-on: ${{ matrix.os }}
    env:
      GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    outputs:
      artifacts: ${{ steps.upload.outputs.artifacts }}
    needs: release

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        build: [win, mac, linux]

    steps:
      - name: Check out git repository
        uses: actions/checkout@v3.0.0

      - name: Install Node.js
        uses: actions/setup-node@v3.0.0
        with:
          node-version: "18.12.0"

      - name: Install Dependencies
        run: npm install

      - name: Build Electron App
        run: npm run build:${{ matrix.build }}

      - name: Cleanup Artifacts
        run: |
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            npx rimraf "dist/!(*.exe)"
          elif [ "${{ matrix.os }}" == "macos-latest" ]; then
            npx rimraf "dist/!(*.dmg)"
          fi

      - name: Upload artifacts
        id: upload
        uses: actions/upload-artifact@v3.0.0
        with:
          name: ${{ matrix.os }}
          path: dist

      - name: Release
        uses: softprops/action-gh-release@v0.1.14
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: ${{ needs.release.outputs.artifacts }}
