name: Build

on:
  push:
    branches:
      - dev
    tags:
      - v*
jobs:
  release:
    name: Build and release electron app
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Check out git repository
        uses: actions/checkout@v3.0.0

      - name: Install Node.js
        uses: actions/setup-node@v3.0.0
        with:
          node-version: "18.12.0"

      - name: Install Dependencies
        run: npm install

      - name: Build Electron App For Win
        if: matrix.os == 'windows-latest'
        run: npm run build:win

      - name: Build Electron App For Mac
        if: matrix.os == 'macos-latest'
        run: npm run build:mac

      - name: Build Electron App For Linux
        if: matrix.os == 'ubuntu-latest'
        run: npm run build:linux

      - name: Cleanup Artifacts for Windows
        if: matrix.os == 'windows-latest'
        run: |
          npx rimraf "dist/!(*.exe)"

      - name: Cleanup Artifacts for MacOS
        if: matrix.os == 'macos-latest'
        run: |
          npx rimraf "dist/!(*.dmg)"

      - name: Upload artifacts
        uses: actions/upload-artifact@v3.0.0
        with:
          name: ${{ matrix.os }}
          path: dist

      - name: Create a release
        uses: softprops/action-gh-release@v0.1.14
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: "dist/**"
