name: Build Release

on:
  push:
    tags:
      - v*

jobs:
  build-windows:
    name: Build for Windows
    runs-on: windows-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v3.0.0

      - name: Install Node.js
        uses: actions/setup-node@v3.0.0
        with:
          node-version: "16.x"

      - name: Install Dependencies
        run: npm install

      - name: Build Electron App for Windows
        run: npm run build:win
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: SPlayer-Windows
          path: dist/*.exe

  build-macos:
    name: Build for macOS
    runs-on: macos-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v3.0.0

      - name: Install Node.js
        uses: actions/setup-node@v3.0.0
        with:
          node-version: "16.x"

      - name: Install Dependencies
        run: npm install

      - name: Build Electron App for macOS
        run: npm run build:mac
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: SPlayer-macOS
          path: dist/*.dmg

  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v3.0.0

      - name: Install Node.js
        uses: actions/setup-node@v3.0.0
        with:
          node-version: "16.x"

      - name: Install Dependencies
        run: npm install

      - name: Build Electron App for Linux
        run: npm run build:linux
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: SPlayer-Linux
          path: dist/*.AppImage

  create-release:
    needs: [build-windows, build-macos, build-linux]
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3.0.0
        
      - name: Create a release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: "dist/**"
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
