name: release

on:
  push:
    tags:
      - v*

jobs:
  mac_release:
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm

      - run: npm ci
      - run: npm run build:mac

      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: mac-release
          path: release/*/*.*

      - name: Create a release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: release/mac-release/*.*

  windows_release:
    runs-on: windows-latest
    timeout-minutes: 30

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm

      - run: npm ci
      - run: npm run build:win

      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: windows-release
          path: release/*/*.*

      - name: Create a release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: release/windows-release/*.*

  linux_release:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm

      - run: npm ci
      - run: npm run build:linux

      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: linux-release
          path: release/*/*.*

      - name: Create a release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: release/linux-release/*.*
